// ignore_for_file: unused_field, type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@internal
@ffi.DefaultAsset('package:ptyx/ptyx.dart')
library;

import 'dart:ffi' as ffi;
import 'package:meta/meta.dart' show internal;

@ffi.Native<ffi.Uint32 Function()>()
external int ptyx_abi_version_major();

@ffi.Native<ffi.Uint32 Function()>()
external int ptyx_abi_version_minor();

@ffi.Native<status Function(ffi.Pointer<session>, ffi.Uint64)>()
external int ptyx_ack_output(ffi.Pointer<session> session$1, int byte_count);

@ffi.Native<status Function(ffi.Size, ffi.Pointer<ffi.Pointer<owned_buffer>>)>()
external int ptyx_buffer_alloc(
  int capacity,
  ffi.Pointer<ffi.Pointer<owned_buffer>> out_buffer,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Pointer<owned_buffer>)>()
external ffi.Pointer<ffi.Uint8> ptyx_buffer_data(
  ffi.Pointer<owned_buffer> buffer,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<owned_buffer>)>()
external void ptyx_buffer_free(ffi.Pointer<owned_buffer> buffer);

@ffi.Native<ffi.Void Function(ffi.Pointer<session>)>()
external void ptyx_close(ffi.Pointer<session> session$1);

@ffi.Native<status Function(ffi.Pointer<session>, ffi.Pointer<ffi.Uint64>)>()
external int ptyx_get_child_pid(
  ffi.Pointer<session> session$1,
  ffi.Pointer<ffi.Uint64> out_pid,
);

@ffi.Native<status Function(ffi.Pointer<session>, ffi.Pointer<size>)>()
external int ptyx_get_size(
  ffi.Pointer<session> session$1,
  ffi.Pointer<size> out_size,
);

@ffi.Native<status Function(ffi.Pointer<session>, ffi.Pointer<term_mode>)>()
external int ptyx_get_term_mode(
  ffi.Pointer<session> session$1,
  ffi.Pointer<term_mode> out_mode,
);

@ffi.Native<
  status Function(
    ffi.Pointer<session>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int ptyx_get_tty_name(
  ffi.Pointer<session> session$1,
  ffi.Pointer<ffi.Char> buffer,
  ffi.Pointer<ffi.Size> inout_len,
);

@ffi.Native<status Function(ffi.Pointer<ffi.Void>)>()
external int ptyx_init(ffi.Pointer<ffi.Void> dart_initialize_api_dl_data);

@ffi.Native<ffi.Bool Function(ffi.Pointer<session>, ffi.Int32)>()
external bool ptyx_kill(ffi.Pointer<session> session$1, int signal);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> ptyx_last_error_message();

@ffi.Native<status Function(ffi.Pointer<session>, size)>()
external int ptyx_resize(ffi.Pointer<session> session$1, size size$1);

@ffi.Native<ffi.Void Function(ffi.Pointer<session_options>)>()
external void ptyx_session_options_init(ffi.Pointer<session_options> options);

@ffi.Native<
  status Function(
    ffi.Pointer<session_options>,
    ffi.Pointer<ffi.Pointer<session>>,
  )
>()
external int ptyx_spawn(
  ffi.Pointer<session_options> options,
  ffi.Pointer<ffi.Pointer<session>> out_session,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(status)>()
external ffi.Pointer<ffi.Char> ptyx_status_string(int status$1);

@ffi.Native<
  status Function(ffi.Pointer<session>, ffi.Pointer<ffi.Uint8>, ffi.Size)
>()
external int ptyx_write(
  ffi.Pointer<session> session$1,
  ffi.Pointer<ffi.Uint8> data,
  int length,
);

@ffi.Native<
  status Function(ffi.Pointer<session>, ffi.Pointer<owned_buffer>, ffi.Size)
>()
external int ptyx_write_owned(
  ffi.Pointer<session> session$1,
  ffi.Pointer<owned_buffer> buffer,
  int length,
);

const int PTYX_ABI_VERSION_MAJOR = 11;

const int PTYX_ABI_VERSION_MINOR = 0;

const int PTYX_ENV_CLEAR = 3;

const int PTYX_ENV_INHERIT = 0;

const int PTYX_ENV_OVERLAY = 1;

const int PTYX_ENV_REPLACE = 2;

const int PTYX_ERROR_SOURCE_MODE = 4;

const int PTYX_ERROR_SOURCE_OUTPUT = 1;

const int PTYX_ERROR_SOURCE_WAIT = 3;

const int PTYX_ERROR_SOURCE_WRITE = 2;

const int PTYX_EVENT_ERROR = 2;

const int PTYX_EVENT_EXIT = 1;

const int PTYX_EVENT_TERM_MODE = 3;

const int PTYX_MESSAGE_CLOSED = 2;

const int PTYX_MESSAGE_OUTPUT = 1;

const int PTYX_SESSION_ENABLE_MODE_EVENTS = 2;

const int PTYX_SESSION_OUTPUT_EXTERNAL_TYPED_DATA = 1;

const int PTYX_SESSION_REQUIRE_OUTPUT_ACKS = 4;

const int PTYX_STATUS_BROKEN_PIPE = 15;

const int PTYX_STATUS_BUFFER_TOO_SMALL = 8;

const int PTYX_STATUS_BUSY = 18;

const int PTYX_STATUS_CLOSED = 6;

const int PTYX_STATUS_EOF = 14;

const int PTYX_STATUS_ERROR = 1;

const int PTYX_STATUS_INVALID_ARGUMENT = 2;

const int PTYX_STATUS_IO_FAILED = 10;

const int PTYX_STATUS_NATIVE_ERROR = 19;

const int PTYX_STATUS_OK = 0;

const int PTYX_STATUS_OUT_OF_MEMORY = 4;

const int PTYX_STATUS_PERMISSION_DENIED = 16;

const int PTYX_STATUS_SPAWN_FAILED = 9;

const int PTYX_STATUS_TIMEOUT = 12;

const int PTYX_STATUS_UNSUPPORTED = 3;

const int PTYX_STATUS_WAIT_FAILED = 11;

const int PTYX_STATUS_WOULD_BLOCK = 7;

const int PTYX_TERM_MODE_CANONICAL_VALID = 1;

const int PTYX_TERM_MODE_ECHO_VALID = 2;

const int PTYX_TERM_MODE_SIGNALS_VALID = 4;

typedef env_mode = ffi.Uint32;
typedef Dartenv_mode = int;
typedef flags = ffi.Uint32;
typedef Dartflags = int;
typedef owned_buffer = ptyx_owned_buffer;

final class ptyx_owned_buffer extends ffi.Opaque {}

final class ptyx_session extends ffi.Opaque {}

final class ptyx_session_options extends ffi.Struct {
  @flags()
  external int flags$1;

  external string executable;

  external ffi.Pointer<string> argv;

  @ffi.Size()
  external int argc;

  external ffi.Pointer<string> env_items;

  @ffi.Size()
  external int env_count;

  @env_mode()
  external int env_mode$1;

  external string cwd;

  external size initial_size;

  @ffi.Int64()
  external int output_port;

  @ffi.Int64()
  external int event_port;

  @ffi.Uint32()
  external int read_buffer_size;

  @ffi.Uint32()
  external int output_batch_max_bytes;

  @ffi.Uint32()
  external int output_batch_max_delay_us;

  @ffi.Uint32()
  external int mode_poll_interval_ms;

  @ffi.Uint64()
  external int max_inflight_bytes;

  @ffi.Uint64()
  external int max_external_output_bytes;

  @ffi.Uint64()
  external int write_queue_max_bytes;
}

final class ptyx_size extends ffi.Struct {
  @ffi.Uint32()
  external int rows;

  @ffi.Uint32()
  external int columns;

  @ffi.Uint32()
  external int pixel_width;

  @ffi.Uint32()
  external int pixel_height;
}

final class ptyx_string extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Size()
  external int len;
}

final class ptyx_term_mode extends ffi.Struct {
  @flags()
  external int valid_fields;

  @ffi.Bool()
  external bool canonical;

  @ffi.Bool()
  external bool echo;

  @ffi.Bool()
  external bool signals;
}

typedef session = ptyx_session;
typedef session_options = ptyx_session_options;
typedef size = ptyx_size;
typedef status = ffi.Uint32;
typedef Dartstatus = int;
typedef string = ptyx_string;
typedef term_mode = ptyx_term_mode;
